* Links 
** DropWizard
   [[https://www.dropwizard.io/en/latest/manual/core.html][Dropwizard Core]]
   [[https://www.dropwizard.io/en/latest/manual/core.html#managed-objects][DropWizard Managed Objects]]
   [[https://howtodoinjava.com/dropwizard/tutorial-and-hello-world-example/][Dropwizard Tutorial – Hello World Example]]
** Avro, Schema
   [[http://avro.apache.org/docs/current/gettingstartedjava.html][Apache Avro™ 1.10.0 Getting Started (Java)]]
   Docs Build Applications for Kafka -> [[https://docs.confluent.io/current/schema-registry/index.html][Schema Management]] (Confluent)
   [[https://docs.confluent.io/current/schema-registry/schema_registry_tutorial.html#schema-registry-tutorial][Schema Registry Tutorials]] / [[https://docs.confluent.io/current/schema-registry/schema_registry_onprem_tutorial.html#schema-registry-onprem-tutorial][On-Premises Schema Registry Tutorial]] (Confluent)
** Kafka
** [[https://liveproject.manning.com/project/153/52/managing-a-distributed-electrical-grid-in-real-time-with-kafka?][Live Project]]
* Project phase 1 - Ingesting Streaming Events and Realtime Access to Battery State
** The Data Fields

   The following table specifies the fields in the data that are received from the IoT device 
   and are processed by our server. 
   #+NAME: device-event-fields-table
   |------------------+-----------+---------------+-----------+--------------|
   | Field name       | Avro type | Avro nullable | Java type | Where        |
   |------------------+-----------+---------------+-----------+--------------|
   | device_id        | string    | t             | String    | pojo avro db |
   | charging         | int       | T             | int       | pojo avro db |
   | charging_source  | string    | T             | String    | pojo avro db |
   | current_capacity | int       | y             | int       | pojo avro db |
   | moduleL_temp     | int       | y             | int       | pojo avro db |
   | moduleR_temp     | int       | y             | int       | pojo avro db |
   | processor1_temp  | int       | y             | int       | pojo avro db |
   | processor2_temp  | int       | y             | int       | pojo avro db |
   | processor3_temp  | int       | y             | int       | pojo avro db |
   | processor4_temp  | int       | y             | int       | pojo avro db |
   | inverter_state   | int       | y             | int       | pojo avro db |
   | soc_regulator    | float     | y             | float     | pojo avro db |
   | received_when    | long      | T             | long      | avro db      |
   |------------------+-----------+---------------+-----------+--------------|


   #+NAME: device-event-fields-table-save
   |------------------+-----------+---------------+-----------+--------------|
   | Field name       | Avro type | Avro nullable | Java type | Where        |
   |------------------+-----------+---------------+-----------+--------------|
   | device_id        | string    | t             | String    | pojo avro db |
   | charging         | int       | T             | int       | pojo avro db |
   | charging_source  | string    | T             | String    | pojo avro db |
   | current_capacity | int       | y             | int       | pojo avro db |
   | moduleL_temp     | int       | y             | int       | pojo avro db |
   | moduleR_temp     | int       | y             | int       | pojo avro db |
   | processor1_temp  | int       | y             | int       | pojo avro db |
   | processor2_temp  | int       | y             | int       | pojo avro db |
   | processor3_temp  | int       | y             | int       | pojo avro db |
   | processor4_temp  | int       | y             | int       | pojo avro db |
   | inverter_state   | int       | y             | int       | pojo avro db |
   | soc_regulator    | int       | y             | int       | pojo avro db |
   | received_when    | long      | T             | long      | avro db      |
   | id               |           |               | int       | db           |
   |------------------+-----------+---------------+-----------+--------------|

** Generate Files
*** Helper functions
    #+NAME: helper_functions 
    #+BEGIN_SRC emacs-lisp
	    (defun in-pojo-p (where)
	      "Return T when 'pojo' occurs in where."
	      (string-match-p (regexp-quote "pojo") where))

	    (defun in-avro-p (where)
	      "Return T when 'avro' occurs in where."
	      (string-match-p (regexp-quote "avro") where))

	    (defun in-db-p (where)
	      "Return T when 'db' occurs in where."
	      (string-match-p (regexp-quote "db") where))

	    (defun fieldname-col (row)
	      "Return the value from the Field name column in row."
	      (nth 0 row))

	    (defun avrotype-col (row)
	      "Return the value from the Avro type column in row."
	      (nth 1 row))

	    (defun avronullable-p (row)
	      "Return T when the value from the Avro nullable column in row contains T t Y or y."
	      (let ((ns (nth 2 row)))
		(if (string-match-p "[TtYy]" ns)
		    ns
		  nil
		  )
		))

	    (defun javatype-col (row)
	      "Return the value from the Jave type column in row."
	      (nth 3 row))

	    (defun where-col (row)
	      "Return the value from the Where column in row."
	      (nth 4 row))

	    (defun capfirst (text)
	      "Uppercase the first character in text."
	      (let ((frst (substring text 0 1))
		    (rest (substring text 1 nil)))
		(concat
		 (upcase frst)
		 rest)))
    #+END_SRC

    #+RESULTS: helper_functions
    : capfirst

    #+RESULTS:
    : capfirst

*** DeviceEvent Pojo
    #+NAME: pojo_functions 
    #+BEGIN_SRC emacs-lisp
      (defun deviceevent-pojo-fields (datarows)
	"Generate the private data fields in the Pojo."
	  (let ((output ""))
	    (dotimes (i (length datarows) output)
	      (let ((rowi (nth i datarows)))
		(let ((fieldname (fieldname-col rowi))
		      (javatype  (javatype-col  rowi))
		      (inpojo    (in-pojo-p     (where-col rowi))))
		  (if inpojo
		      (setq output
			    (concat
			     output
			     "    private " javatype " " fieldname ";\n"
			     "    @JsonProperty\n"
			     "    public " javatype " get" (capfirst fieldname) "() {\n"
			     "        return " fieldname ";\n"
			     "    }\n\n"
			     ))))))
	      output
	))
      (defun deviceevent-pojo-getters (datarows)
	"Generate the Getters in the Pojo."
	""
	)
      (defun generate-deviceevent-pojo (datarows)
	(let ((pojo-output
	       (concat
		"package com.example.ingestbattevents.api;\n"
		"import com.fasterxml.jackson.annotation.JsonProperty;\n"
		"\n"
		"public class DeviceEvent {\n"
		"\n"
		"    public DeviceEvent() {\n"
		"        // Jackson deserialization\n"
		"    }\n"
		"\n"
		(deviceevent-pojo-fields datarows)
		"\n"
		"}\n"
		)))

	  (with-temp-buffer
	    (let ((outfile "scaffold/src/main/java/api/DeviceEvent.java"))
	      (insert pojo-output)
	      (when (file-writable-p outfile)
		(write-region (point-min)
			      (point-max)
			      outfile))))))
    #+END_SRC

    #+RESULTS: pojo_functions
    : generate-deviceevent-pojo

    #+RESULTS:
    : generate-deviceevent-pojo

*** DeviceEvent Avro Schema
    #+NAME: avro_functions 
    #+BEGIN_SRC emacs-lisp
      (defun deviceevent-avroschema-default (avrotype)
	"Return the default value for the given AVRO type."
	(cond
	 ((string= avrotype "boolean") "false")
	 ((string= avrotype "int"    ) "0"    )
	 ((string= avrotype "long"   ) "0"    )
	 ((string= avrotype "float"  ) "0.0"  )
	 ((string= avrotype "double" ) "0.0"  )
	 ((string= avrotype "string" ) "\"\"" )
	 (t                            nil    )
	 )
	)
      (defun deviceevent-avroschema-type (avrotype nullable)
	"Return the type to be used in the AVRO schema."
	(let ((atp (concat "\"" avrotype "\"")))
	  (if nullable
	      (concat "[" atp ", \"null\"]")
	    atp
	    )))
      (defun deviceevent-avroschema-keyvalue (key value)
	"Return a JSON formatted key-value pair."
	(concat "\"" key "\": " value)
	)
      (defun deviceevent-avroschema-fields (datarows)
	"Generate the data fields part of the schema."
	  (let ((output ""))
	    (dotimes (i (length datarows) output)
	      (let ((rowi (nth i datarows)))
		(let ((fieldname (fieldname-col  rowi))
		      (avrotype  (avrotype-col   rowi))
		      (nullable  (avronullable-p rowi))
		      (inavro    (in-avro-p     (where-col rowi))))
		  (if inavro
		      (setq output
			    (concat
			     output
			     (if (> (length output) 0)
				 "    ,"
			       "    ")
			     "{\n"
			     "        \"name\": \"" fieldname "\",\n"
			     ;;"        \"type\": [\"string\", \"null\"],\n"
			     ;;"        \"type\": " avrotype ",\n"
			     "        " (deviceevent-avroschema-keyvalue "type" (deviceevent-avroschema-type avrotype nullable)) ",\n"
			     "        " (deviceevent-avroschema-keyvalue "default" (deviceevent-avroschema-default avrotype)) "\n"
			     "    }\n"
			     ;; "    private " javatype " " fieldname ";\n"
			     ;; "    @JsonProperty\n"
			     ;; "    public " javatype " get" (capfirst fieldname) "() {\n"
			     ;; "        return " fieldname ";\n"
			     ;; "    }\n\n"
			     ))))))
	      output
	))
      (defun generate-deviceevent-avroschema (datarows)
	(let ((avroschema-output
	       (concat
		"{\n"
		"  \"namespace\": \"com.example.ingestbattevents.avro\",\n"
		"  \"type\": \"record\",\n"
		"  \"name\": \"DeviceEventAvro\",\n"
		"  \"fields\": [\n"
		(deviceevent-avroschema-fields datarows)
		;; "    {\n"
		;; "        \"name\": \"device_id\",\n"
		;; "        \"type\": [\"string\", \"null\"],\n"
		;; "        \"default\": \"\"\n"
		;; "    }\n"
		;; "    ,{\n"
		;; "        \"name\": \"charging\",\n"
		;; "        \"type\": [\"int\",\"null\"],\n"
		;; "        \"default\": 0\n"
		;; "    }\n"
		;; "    ,{\n"
		;; "        \"name\": \"charging_source\",\n"
		;; "        \"type\": [\"string\", \"null\"],\n"
		;; "        \"default\": \"\"\n"
		;; "    }\n"
		;; "    ,{\n"
		;; "        \"name\": \"current_capacity\",\n"
		;; "        \"type\": [\"int\",\"null\"],\n"
		;; "        \"default\": 0\n"
		;; "    }\n"
		"    ]\n"
		"}\n"
		)))

	  (with-temp-buffer
	    (let ((outfile "scaffold/src/main/resources/avro/deviceevent.avsc"))
	      (insert avroschema-output)
	      (when (file-writable-p outfile)
		(write-region (point-min)
			      (point-max)
			      outfile))))))
    #+END_SRC

    #+RESULTS: avro_functions
    : generate-deviceevent-avroschema

    #+RESULTS:
    : generate-deviceevent-avroschema

    #+RESULTS: generate-deviceevent-pojo
    : generate-deviceevent-dbimodule

*** DeviceEvent Dbi module
    #+NAME: dbi_functions 
    #+BEGIN_SRC emacs-lisp
      (defun generate-deviceevent-dbimodule (datarows)
	(let ((dbimodule-output
	       (concat
		"// =====================\n"
		"// DeviceEvent Dbi module\n"
		"// =====================\n"
		"\n"
		)))

	  (with-temp-buffer
	    (let ((outfile "scaffold/src/main/java/dbi/DeviceEvent.java"))
	      (insert dbimodule-output)
	      (when (file-writable-p outfile)
		(write-region (point-min)
			      (point-max)
			      outfile))))))
    #+END_SRC

    #+RESULTS: dbi_functions
    : generate-deviceevent-dbimodule

    #+RESULTS:
    : generate-deviceevent-dbimodule

*** Top-level function
    #+NAME: generate-for-device-event
    #+BEGIN_SRC emacs-lisp
      (let ((datarows (cdr tbl)))
	(progn (generate-deviceevent-pojo       datarows)
	       (generate-deviceevent-avroschema datarows)
	       ;;(generate-deviceevent-dbimodule  datarows)
	       ))
    #+END_SRC

    #+RESULTS:
    : generate-for-device-event

*** The call to top-level function
#+CALL: generate-for-device-event(tbl=device-event-fields-table) :colnames no

#+RESULTS:

** The Device Event generator
*** Source File [[event-generators/src/main/java/com/jesseyates/manning/EventGenerator.java][EventGenerator.java]] contains a hashmap with possible event fields:
   #+begin_src java
   (...)
   // setup event field values
   {
     events.put("charging", new ImmutablePair<>(-1000, 1000));
     events.put("charging_source", new ImmutablePair<>("solar", "utility"));
     events.put("current_capacity", new ImmutablePair<>(0, 13_000));
     // other fields like a real device would send
     // events.put("moduleL_temp", new ImmutablePair<>(-5, 225));
     // events.put("moduleR_temp", new ImmutablePair<>(-5, 225));
     // events.put("processor1_temp", new ImmutablePair<>(-5, 225));
     // events.put("processor2_temp", new ImmutablePair<>(-5, 225));
     // events.put("processor3_temp", new ImmutablePair<>(-5, 225));
     // events.put("processor4_temp", new ImmutablePair<>(-5, 225));
     // events.put("inverter_state", new ImmutablePair<>(0, 15));
     // events.put("SoC_regulator", new ImmutablePair<>(26.0f, 29.6f));
   }
   (...)
   #+end_src
   The generator generates a random number of events with random field values. 
   The event data is then formatted as a JSON array and POST-ed to the web-server.
*** Compiling/running
    $ cd (...)/event-generators
    $ mvn clean/compile/package
    $ java -jar target/event-generators-1.2-SNAPSHOT-jar-with-dependencies.jar events -e 1 --debug -t http://localhost:8080/device-events
** Dropwizard Webserver
*** Receiving POST-ed Device events
    File [[scaffold/src/main/java/DeviceEventResource.java][DeviceEventResource.java]] sets up the URL /device-events/{devid} for receiving 
    device events with charging data for device with id devid. This handler expects 
    an JSON array of device event records that are decoded into an ArrayList<[[/home/bert/DistributedGridProject/manning-energy-resources/scaffold/src/main/java/DeviceEvent.java][DeviceEvent]]>.
*** GET-ting Device Loading information
*** Compiling/running
    $ cd (...)/scaffold
    $ mvn clean/compile/package
    $ java -jar target/energy-kafka-1.0-SNAPSHOT.jar server ingestbattevents.yml
** Avro Schema
*** The Schema file
    File [[scaffold/src/main/resources/avro/devicebattevent.avsc][devicebattevent.avsc]] defines the schema to use when sending/receiving device events to/from Kafka.
    It defines a simple record consisting of a list of fields enumerated in the tables above.
    This results in generated Java code in file [[scaffold/src/main/generated/com/example/ingestbattevents/avro/DeviceEventAvro.java][DeviceEventAvro.java]] that can be used for this purpose.
*** The Java Producer Code to send incoming device event data through to Kafka
    This is a [[https://github.com/confluentinc/examples/blob/6.0.0-post/clients/avro/src/main/java/io/confluent/examples/clients/basicavro/ProducerExample.java][full producer example]].
    The following code was added as a function sendDeviceEventToKafka
    in file [[scaffold/src/main/java/DeviceEventResource.java][DeviceEventResource.java]]:

    #+begin_src java
    import io.confluent.kafka.serializers.KafkaAvroSerializer;
    (...)
    // Added to the DeviceEventResource constructor
    props = ....
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, KafkaAvroSerializer.class);
    (...)
    // Added function
    private void sendDeviceEventToKafka(DeviceEvent deviceevent) {
        KafkaProducer<String, DeviceEventAvro> producer = new KafkaProducer<String, DeviceEventAvro>(props);

        DeviceEventAvro.Builder avrobuilder = DeviceEventAvro.newBuilder();
        DeviceEventAvro eventavro = 
            avrobuilder.setDeviceId       (deviceevent.getDevice_id())
                       .setCharging       (deviceevent.getCharging())
                       .setChargingSource (deviceevent.getCharging_source())
                       .setCurrentCapacity(deviceevent.getCurrent_capacity())
                       .build();

        final ProducerRecord<String, DeviceEventAvro> record = new ProducerRecord<String, DeviceEventAvro>(TOPIC, deviceevent.getDevice_id(), eventavro);
        producer.send(record);
    }
    #+end_src
** Running Kafka in container
*** Install Docker c.s.
    [[https://docs.docker.com/engine/install/ubuntu/][install Docker]]
    [[https://docs.docker.com/engine/install/linux-postinstall/][Post-installation steps for Linux]]
    bert@bert-K18Base:~$ sudo groupadd docker
    groupadd: group 'docker' already exists
    bert@bert-K18Base:~$ sudo usermod -aG docker $USER)
    ($ sudo apt install docker-compose)
    $ docker run hello-world
*** Running
    $ cd (...)/scaffold
    $ docker-compose -f docker-compose-kafka.yml up
    $# runs at localhost:29092, schema registry at localhost:8090
**** Log
bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ curl --silent -X GET http://localhost:8090/subjects/ | jq .
[
  "device-events-value"
]
bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ curl --silent -X GET http://localhost:8090/subjects/device-events-value/versions/latest | jq .
{
  "subject": "device-events-value",
  "version": 1,
  "id": 41,
  "schema": "{\"type\":\"record\",\"name\":\"DeviceEventAvro\",\"namespace\":\"com.example.ingestbattevents.avro\",\"fields\":[{\"name\":\"device_id\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"charging\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"charging_source\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"current_capacity\",\"type\":[\"int\",\"null\"],\"default\":0}]}"
}
** Kafka Streams
*** Streams configuration
**** streams.StreamsConfiguration.java#streamsConfiguration sets up a configuration for the streams,
**** streams.StreamsConfiguration.java#schemaRegistry returns a map containing the URL of the schema resistry.
*** Device Event Stream topology
    Look at this example how they use Avro Schema's and serialisation/deserialisation.
    folder: file:///media/bert/Data/Areas/Training/KafkaStreamsTutorials/kafka-streams-examples
    file -> file:///media/bert/Data/Areas/Training/KafkaStreamsTutorials/kafka-streams-examples/src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java

    [[file:///home/bert/DistributedGridProject/manning-energy-resources/scaffold/src/main/java/streams/DeviceEventProcessing.java][streams.DeviceEventProcessing.java]] contains the setup of the device event processing topology.
    This also implements the DropWizard Managed interface, so that the stream can be started/stopped
    when the webserver starts/stops.
    This also calls on StreamsConfiguration to find out where the Kafka Brokers are and
    where the Schema Resistry can be found.

** Storing Events in a Database
   -> (...)/scaffold/README.md
*** PostGreSQL
**** Run/stop/remove PostgreSQL db container
     $ docker run --name manning-postgres -e POSTGRES_PASSWORD=secret -p 5432:5432 -d postgres:12.2
     $ docker stop manning-postgres
     $ docker rm manning-postgres
**** Connect to the db container via CLI
***** [[https://www.postgresql.org/docs/8.1/ddl-schemas.html][Listing Schema's]]
      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ docker ps
      CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
      4b5c7433998c        postgres:12.2       "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:5432->5432/tcp   manning-postgres

      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ docker exec -it manning-postgres psql -U postgres -c “SELECT schema_name FROM information_schema.schemata”
      psql: warning: extra command-line argument "FROM" ignored
      psql: warning: extra command-line argument "information_schema.schemata”" ignored
      psql: error: could not connect to server: FATAL:  database "schema_name" does not exist

***** [[https://www.postgresql.org/docs/9.1/sql-createtable.html][Create a new table]] in the public database:  
      bash $ docker exec -it manning-postgres psql -U postgres \ -c
      "CREATE TABLE devices (uuid varchar, state boolean)"
***** List tables
      bash $ docker exec -it manning-postgres psql -U postgres -c '\dt' List of relations Schema | Name |
      Type | Owner --------+---------+-------+---------- public | devices | table | postgres (1 row)
**** For DropWizard
***** Enable the postgres dependency in the pom, adding the client libraries to the project, 
     allowing to actually connect to the database 
***** Add to [[file:///home/bert/DistributedGridProject/manning-energy-resources/scaffold/ingestbattevents.yml][ingestbattevents.yml]]
     database:
       driverClass: org.postgresql.Driver
       user: postgres
       password: secret
       url: "jdbc:postgresql://0.0.0.0:5432/postgres"
*** [[https://dev.mysql.com/doc/workbench/en/][MySQL Workbench]]
**** Install
     $ nix-env -iA nixpkgs.mysql-workbench
***** Log
      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ nix-env -iA nixpkgs.mysql-workbench
      installing 'mysql-workbench-8.0.21'
      these paths will be fetched (250.78 MiB download, 1584.30 MiB unpacked):
      /nix/store/027haj2r42a8997xy0gxszazdn5dpx9m-libzip-1.6.1
      /nix/store/03xvf19yd2d4j6f4ppanyxzhfv2b1h0z-atkmm-2.28.0
      /nix/store/06ymz7xipyybjn1pmxcpn3zzbm1bxk50-freetype-2.10.4
      /nix/store/0764z6qz8s7gkwas1i88zwvvbzpmivry-libXau-1.0.9
      /nix/store/09v32i77zl9dpy0wyfvh5w60mjcn5qnc-pangomm-2.42.1
      /nix/store/0f3ai525f7cmr65k7ni89crskjjj60cf-unbound-1.12.0-lib
      /nix/store/10k4rvwvsvb65jywky7sd5626jaby4s6-python2.7-paramiko-2.7.1
      /nix/store/12smikrbb26awn8kb93jzgjibda9i9j9-libpng-apng-1.6.37-dev
      /nix/store/159apbdmiwk945209nbq7jb6rnmh363d-geos-3.8.1
      /nix/store/165sgncsp2fmmjcibjihvfyvbdd5rsv4-qhull-2016.1
      /nix/store/18lvqs6xfmda6rspfyklf3978a1axwrr-libedit-20191231-3.1
      /nix/store/19p49h93x1zv7zmrpc3myrxr9c95w788-iptables-1.8.5
      /nix/store/1fmgf62158i2ys89m4m983z4d8nx1630-libnetfilter_conntrack-1.0.8
      /nix/store/1k6wsg0a3wlyfyfqfawyz3ccdba84mms-libXinerama-1.1.4
      /nix/store/1lql50lys0rwn2102a4krpgcwi0ys4kz-libcap-2.44-lib
      /nix/store/1nqmm3yj772g38vlrk2y80xy59vq0442-linux-pam-1.3.1
      /nix/store/1qv0pm4j52lfagsw90ax8przd0cfg8cz-cups-2.3.3-lib
      /nix/store/1xm6cjbyv6005rxiqkzbavr9swmiygdm-libXcursor-1.2.0
      /nix/store/23gri5n5jxn96jjr5p0rcy2145d6s1bl-db-4.8.30
      /nix/store/23r068n28wqhp619v4jw4cvlvs67xp6d-hdf-4.2.15-dev
      /nix/store/2fz4hd2gw73y7di274bdpq0bw2hxnfqa-libgeotiff-1.5.1
      /nix/store/2kbpfcpagl62m17bg3apa6pm24vydny1-libossp-uuid-1.6.2
      /nix/store/2l0kc0lx8122pbzysm2ss5xscirq0j33-poppler-glib-20.08.0
      /nix/store/2shqhfsyzz4rnfyysbzgyp5kbfk29750-coreutils-8.32
      /nix/store/2x8cm493hnkh2zxcich3fpm82m5vrpq8-fribidi-1.0.7
      /nix/store/3725gkhcvwdknqp0b51mx7wpva56faxr-lvm2-2.03.10-lib
      /nix/store/3g1lrr95qmyc80gfn1n1mddx66d3p98r-fontconfig-2.13.92-lib
      /nix/store/3wsi43smyzkk0q2fb299yrrgriwilams-iso-codes-4.5.0
      /nix/store/3y1l12ydwzsa594ylzij36v7zjl54h1c-libiodbc-3.52.12
      /nix/store/42dx4mzml1jq6p9mjrlm1zimywq1n0r8-python2.7-cffi-1.14.2-dev
      /nix/store/42n8wzfsd98xh9i02sm9ikzsxi2921ja-pango-1.45.3
      /nix/store/478qa0dmvj9d2ra9gpda0ykdpgj78nhp-nettle-3.6
      /nix/store/4bz9ysliadpg73rm0h0gc87b0cpjg19m-at-spi2-atk-2.34.2
      /nix/store/4rm9zps0vcz8f65jb8y41djdpllixbqx-cairo-1.16.0
      /nix/store/4zxwvbg07ypnlh6r78kp3swcy93919a3-hdf-4.2.15
      /nix/store/57yia67ixw99ahy6s5cal6y22kk1mcr5-hdf5-1.10.6
      /nix/store/5f61vfhr8rzyjywmrdzbxh3ych62xcri-libkrb5-1.18
      /nix/store/5h5qnaypmrc1d706w66vwhnynwh20qjm-gzip-1.10
      /nix/store/5mzp7cdjlwmj29cvyba2ag3s1p96lfpc-python2.7-pynacl-1.4.0
      /nix/store/5pq125diq416cz6fvam7mf7c65c09imw-librsvg-2.48.8
      /nix/store/622p9d64jgzdka252fzd17ljxs3m3ar2-kbd-2.0.4
      /nix/store/6cn64xk3n5723afx62f22ld77dil7cbc-boost-1.59.0-dev
      /nix/store/6lc0s5wnppzb1526vnlxiq34h1l01460-libssh2-1.9.0
      /nix/store/6p9bqmsl15490izwpzvjqhbfa271ni9y-openssl-1.1.1h
      /nix/store/6rxn3knmprqf2sd1gmbqrmxi2s538vnl-libseccomp-2.5.0-lib
      /nix/store/6wzc17mfz9qn9gbbp2kzhcaf7c80hgdl-libjpeg-turbo-2.0.5-dev
      /nix/store/6yfafnp1ssjksj6bnks969h8zanm7q6m-poppler-data-0.4.9
      /nix/store/74sd6nrnxiafn2l4mdwz4h7wz2wnx90a-pixman-0.38.4
      /nix/store/77k2a0jm8n55ympnxqpwmzv4s2hdq69i-keyutils-1.6.3-lib
      /nix/store/78d1i8bhnd1flnxk1srpjm2fbdli6fls-harfbuzz-2.7.2
      /nix/store/7bpq6jhxdans9csm7brrdj0qg8bk0m8v-libidn2-2.3.0
      /nix/store/7r9v0hzwrrm9lh6c990fflrzwi36j7hf-gnupg-2.2.23
      /nix/store/89xa9b33wlxhmkxhflp8gfdb8n2nn5y4-libsecret-0.20.3
      /nix/store/8f13dxfh1rs0zxb13m39hnsysapqg9vc-json-c-0.14
      /nix/store/8fcxqg8dmwlkjw2vgkgz607kr5jy552w-zlib-1.2.11
      /nix/store/8k0i6x3nlbqjj4p0sc2jadc7l7by75x8-libjpeg-turbo-2.0.5-bin
      /nix/store/8kmia55bxccdvhx79hg6n56nhlqpw8j7-gsettings-desktop-schemas-3.36.1
      /nix/store/8kv1647yhqd13z571h56rgm2ldm567dm-gnugrep-3.5
      /nix/store/8l6c599l07zw3bbsn270sm54hz4lyais-glibc-2.32-bin
      /nix/store/91m1bh46fj3ykm45lb6kvh89il792pj9-kmod-27
      /nix/store/971nym7avrn2f99ng904rffcpbxjplbr-libpcap-1.9.1
      /nix/store/9myly8vmha57m1jwrlxzhsvkiamvl97x-sqlite-3.33.0
      /nix/store/9qh6ck8d9ill2zan91rsnf4ba30hpf95-libselinux-2.9
      /nix/store/9svfnzisqwsxzc0av6yksh7b1pcbb553-libmnl-1.0.4
      /nix/store/9xnc99n9lvv59nwad16zi73bi3z83z8v-ncurses-6.2-dev
      /nix/store/a832yyp1xziag0h0kvy8zrcqwzkzy7hg-proj-6.3.1-dev
      /nix/store/aa8wbrx8b9pjwa3wwdwhf51zmdli26hx-libxkbcommon-0.10.0
      /nix/store/aipbaqh6svp2mssslwlmxjwrlqgyvxxy-dejavu-fonts-minimal-2.37
      /nix/store/aj29saxhbnw9ng35ix46rnzfyvpnaxsm-python2.7-cffi-1.14.2
      /nix/store/ajafywz2virg6zf1yvjwyls69x3ic60j-pcre2-10.35
      /nix/store/apni99c9rdaii9xvsmf1x65dvwgsaxj0-sqlite-3.33.0-bin
      /nix/store/av86g78lzflpxhkq4g9i3r6ab5p1ri2v-libtirpc-1.2.7-rc4
      /nix/store/ayx1hkfwar23xvlfn4l7f8444fhmnmk7-libxcb-1.14
      /nix/store/b5cws72ynps2xyhy74fxdqmsf7a8f472-libffi-3.3-dev
      /nix/store/b6h8w51kl4cpv3r2h6xrpr3injqh99yy-avahi-0.7
      /nix/store/bbyw2n7f771z85nk647znlri22izwm2y-gdk-pixbuf-2.40.0
      /nix/store/bfr66vwyasj7km8zbxv41qiihlss9165-libpng-apng-1.6.37
      /nix/store/blk092jlzlqs4wrasfaciggwbxpbn694-linux-headers-5.5
      /nix/store/bnc6mfjy52lsr81ikyw3kdf7qdqabgvx-bzip2-1.0.6.0.1-bin
      /nix/store/bnjps68g8ax6abzvys2xpx12imrx8949-binutils-2.31.1
      /nix/store/bxh0rnxyjqbbw2zvj9ajra169bcqwsr9-xz-5.2.5
      /nix/store/c7q9fig0zp7v12ys4x8w43bysi8h2jqs-icu4c-67.1-dev
      /nix/store/cghlhk1j0s07mv08vg4wxsn514lzmyzi-mysql-workbench-8.0.21
      /nix/store/clnhaz7q45hna5xj0x7lmayc0hr3mzd3-dbus-1.12.20-lib
      /nix/store/cwbdra0bd32091s1vfrm7m4aq9xrb56r-libXdmcp-1.1.3
      /nix/store/cwc3rnn0lhpq77cwan20cji0w7lhg33y-libGL-1.3.2
      /nix/store/cyaf9gyinfhv7xzpnxsvfm0mg0haq21x-libXrender-0.9.10
      /nix/store/d3vh8xya1pq91lmlh01j74wgb57g7qvv-pcre-cpp-8.44
      /nix/store/dahgbm8aivbr50w80mjrwzs8nsh9a253-shadow-4.8.1
      /nix/store/daj9qsd3ickv1ygn37zmri0ir6wpqv53-epoxy-1.5.4
      /nix/store/dakvjq52bjajv6vskawim9fs3amqgfi5-libdaemon-0.14
      /nix/store/dc09a64gfksp9wi4gx1kxzwwzzw4bvq9-libgpg-error-1.38
      /nix/store/djg5df35m2wnvr9d974iz19gylk07yb9-giflib-5.2.1
      /nix/store/djkgh2mz72lgf849mpcpl2yzn84ibizs-kexec-tools-2.0.20
      /nix/store/dpy5i9qymncg7brd2xi23k56ax9jg2zm-openssl-1.1.1h-bin
      /nix/store/dzj9gs5iir5j8nn2wshsh6i9l6v4zqli-mysql-5.7.27
      /nix/store/f2ix29b5yp5zjl4sxsy6xj4n775qa43d-xz-5.2.5-dev
      /nix/store/f9b4nrlv3an2mqq6772h134za8f3z4rg-libtasn1-4.16.0
      /nix/store/f9jcpi36wgwvf1lh7c68mx7k87xihgqz-python2.7-cryptography-2.9.2
      /nix/store/fg73gb66fnzlv9b9kc1bn1zvdq6w2dn4-acl-2.2.53
      /nix/store/fir9pdbqlvhr05hp9qvyd2nblac3lp60-libtiff-4.1.0
      /nix/store/fn7m5cg0r2806hl6rvm8088d8yzffrr5-popt-1.16
      /nix/store/fq884ddqqa9pg5gxngi1534g81ns2bf3-sqlite-3.33.0-dev
      /nix/store/g4gg2yqpv2lsj4vhrza1nijnzl07gg1c-boost-1.69.0-dev
      /nix/store/g6z1kb94ff1x959jbj2mnx8rbmapb4ij-python2.7-packaging-20.4
      /nix/store/gkz2jxfg0zi1xyra1b8xlyiqb2ngaskd-bzip2-1.0.6.0.1
      /nix/store/gnb3ix8dx5lghj5ccjlfi2kg4l76f8w4-pcre-8.44
      /nix/store/gqni3z3v5v824hq8f9j42s0l3j6318mz-curl-7.73.0
      /nix/store/gvkhgh813chlsvdsnxgwhv72xns08xcp-python3-3.8.6
      /nix/store/gxj03v97cb81039accdxgmmj8srhfbp1-libevent-2.1.12-openssl
      /nix/store/gyfqw8k2ibhn6mcka9mcd7wcmq14cnmm-attr-2.4.48
      /nix/store/h2irg7w6qjmpg6x3dhxw33f3glw3ak5x-icu4c-67.1
      /nix/store/h7x67w9f6fqyyyf31lc0df8xngchck7f-python2.7-pycairo-1.18.2
      /nix/store/hcsw29r90klliqjyfi0z03qdbvg4hf73-libsodium-1.0.18
      /nix/store/hfpiccrc1wsqv9p09mb2ddkakpg09bh4-libunistring-0.9.10
      /nix/store/hgc32jc9wzg1l7xq69an3v6w9m0xj8f1-hdf-4.2.15-bin
      /nix/store/hn84phnkxjn22skjjbrb2jv17xdjprzb-lcms2-2.11
      /nix/store/hq2qa8qfqycbq4yxmpakdydy347axm85-libsigc++-2.10.1
      /nix/store/hq75v8gmnxw132mcg0gxhwflsb3s1p7m-libXrandr-1.5.2
      /nix/store/hr43hbclvklvs08qg9y24pg77nrsmbgl-mysql-8.0.17
      /nix/store/i5iikq61lvkxvhbh5hpk4c1m6zw370pg-libxml2-2.9.10
      /nix/store/i8jx31d2lqh9f55w8vwlgyc1az3jp2pv-fontconfig-2.13.92
      /nix/store/if61207y3w841nq428vqqr7dfsjryvxq-expat-2.2.10
      /nix/store/ikifbdvhhbh1il37lxlr87yb28xqj677-gnutar-1.32
      /nix/store/ilvkcyc9h6b5vg8yxi8gbkajc9044jms-ncurses-6.2
      /nix/store/iq0m232p954skqpgjmwzxx88x9i956zw-re2-20201001
      /nix/store/j2pvv7vdqkzhasxk5v3kix3xl68nhjgn-gcc-9.3.0
      /nix/store/j7hl2d7bwy0ih32002nilzvyy0dx8xyy-libXtst-1.2.3
      /nix/store/jjh1gjjzg4hl10mhy3lblcjinywcn5hl-netcdf-4.7.4
      /nix/store/jq7ikqkazzazydfgghia6n1zww1nnbiq-libglvnd-1.3.2
      /nix/store/jx0ibjlcgljnkwzfj6ij4f763fsns8h0-openssl-1.1.1h-dev
      /nix/store/k3scwx9w0988csgnfy67cxlaj605g87i-binutils-wrapper-2.31.1
      /nix/store/k4sdsvdnxpqckdjxjv0gr5x4jsv0ng4v-libssh-0.8.9
      /nix/store/k8w6yphs1c5a4d5x0ask5k8ycxpp8q7b-python2.7-cryptography-2.9.2-dev
      /nix/store/k9v26smi1999sc167xy7v3bab9sybzk2-python2.7-ipaddress-1.0.23
      /nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32
      /nix/store/kd8i2i3pldbzihcdpv6qgskgxc59374f-libmysqlconnectorcpp-8.0.21
      /nix/store/kp4asqh3waln1m8wka8xbjna1lr7nfap-lz4-1.9.2
      /nix/store/kvsxb0p4qg5s639ngnix9vphcpcr2q2y-systemd-246.6
      /nix/store/lfz94vh4m9c2aygrc48cdsn9pyb4d2d0-graphite2-1.3.14
      /nix/store/lhbdlbqbvmnl9842ag62bynmkgbnp3dq-gcc-9.3.0-lib
      /nix/store/lkl6hyqyw9gvb93mbfbylgdhkbazs3l2-db-5.3.28
      /nix/store/m24r30pk12ckb1hsr9ylg6i7r64jbg38-gmp-6.2.0
      /nix/store/m295m7xbigkh40k4a0cxk16pj7d6h8wb-libapparmor-2.13.5
      /nix/store/m4wghpmj1vbmn2rqk3v19c5m9br03250-antlr-runtime-cpp-4.8
      /nix/store/m67p7i8a45hpd51jjjq39j19vis3wpzs-python2.7-enum34-1.1.10
      /nix/store/m8pgg5z35bs01hyiirwmsv7z8qc8hhcf-nghttp2-1.41.0-lib
      /nix/store/mbszh64fss16x16nj4ffv28qlpdqybr6-p11-kit-0.23.21
      /nix/store/mk5fx9wbsqrbknp6mazgab9vmg336609-openjpeg-2.3.1
      /nix/store/mmbd63kk9r0yi1mppxcwacw7pn9n4x5j-gtkmm-3.24.2
      /nix/store/mz45csnlzibkkrkdvkfm9cwq0j1lv5z7-boost-1.59.0
      /nix/store/n3v2sbh4pvx8pvfnb13wg07vq9x7w9i7-dns-root-data-2019-01-11
      /nix/store/nccvgkfqfdslcjkh448lpchl69sajpny-libICE-1.0.10
      /nix/store/ndfylywxzsc6dkp73cn1k7wdjmifjhbv-libSM-1.2.3
      /nix/store/nichvfjqdfimxmvlhg5q1gs3agiyw9nc-xz-5.2.5-bin
      /nix/store/nvjd9mkfqdzbgbw4gsrj98kvxda7piri-libffi-3.3
      /nix/store/p5iv8pdxi5r4xr65dm5wgr43pkxkjx16-readline-6.3p08
      /nix/store/p71girl88aldyvn2g0h7pn4cjawdrgga-gnutls-3.6.15
      /nix/store/p7hfgpmdzxfbsxg9nn0bcz7nhmj32yh1-libevent-2.1.12
      /nix/store/pdkllhgmkwbp8hdgi3wjdvy1z49l1n1f-gdbm-1.18.1
      /nix/store/pk1hwhw97bsm325gy15v6340m2zh2va7-python2.7-bcrypt-3.1.7
      /nix/store/ppfvi0cfcpdr83klw5kx6si2l260n1gh-gcc-wrapper-9.3.0
      /nix/store/q06qb43z9inljcl8yjp8ll7ihhjkavs0-protobuf-3.7.1
      /nix/store/q2k599dnhcs9p2j3wfiayan73q44w6y5-libXft-2.3.3
      /nix/store/qdp56fi357fgxxnkjrwx1g67hrk775im-bash-4.4-p23
      /nix/store/qdxniv416wbcizfnqbajgq99q8sc1qrp-atk-2.36.0
      /nix/store/qghvmavv2qk81hbg06ghp7qpazvaibdh-bash-interactive-4.4-p23
      /nix/store/qh55gxy4a3msz4kf4iiq0d6zcpq01b54-pkg-config-0.29.2
      /nix/store/qmi3aqa54q02wl7km7i4w1c2ad04f7k0-libXdamage-1.1.5
      /nix/store/qp3pb6bqr5mixb0mmyhrkiq887iy21ms-python2.7-pyodbc-4.0.30
      /nix/store/qsg1y8zjvzad9lfvrzvkf7j6jcz8mzqc-libXext-1.3.4
      /nix/store/qx10kf2vcysr0wvz09g2yh7vwpw0vpn2-numactl-2.0.14
      /nix/store/r898vrribzgp9s502vhm0036nppyarpl-cracklib-2.9.7
      /nix/store/r9h30mp69zcrj8ia0bs98qi1cvkw0ira-util-linux-2.36-bin
      /nix/store/rgisiwcvbwq76r1p4k9r3ybnzck95rkn-ncurses-6.2-man
      /nix/store/rhmffz05dz4zp9szpyrxazd4yz8im38p-gtk+3-3.24.21
      /nix/store/rrl72irws5nay6bkylj6swh8j6k1lnll-vsqlite-0.3.13
      /nix/store/s06hrsni6mxxf3lh61zbznhj0qxy37nr-libtiff-4.1.0-dev
      /nix/store/s3jhwif715gkhbrjhhb5pdv8lq3z2266-boost-1.69.0
      /nix/store/sha4zfj4awli9mrmyzsyaph2pamlck0j-libedit-20191231-3.1-dev
      /nix/store/va2f97v8n2rwnzc7qqy6x6c8rd21nkm9-python2.7-pyparsing-2.4.6
      /nix/store/vd8zcniaj90hb8n445fv3pbf9s9674p6-expat-2.2.10-dev
      /nix/store/vgss4yh5r7fq9pip7mk56dlksrw36h8m-util-linux-2.36
      /nix/store/vhcx1a5m9xscxrmmz7s4nllhcfg5axnn-python-2.7.18
      /nix/store/vjf88s0z78mhnyaggq2jw2a02zvgq1yj-cairomm-1.12.2
      /nix/store/vwlk07g63fdlmdbvikka1wgb0k9nsg0c-systemd-minimal-246.6
      /nix/store/vwmjh73qqcn9djixalzpr0c02lqyhsix-unixODBC-2.3.7
      /nix/store/vy72w62ndpnhwb3wkdq89bbxvg2vqndh-cryptsetup-2.3.4
      /nix/store/w4fqg4x5dzblnib6sr1i75wq2w64hcl7-readline-7.0p5
      /nix/store/w4rfml3w6v1jvpvixih50s12hwcsrjky-libXfixes-5.0.3
      /nix/store/w59b1g3hd5gvwrj21qh38glpywia8lvk-libspatialite-4.3.0a
      /nix/store/w6ly66j38ri54rc712vsl0zf46wz8q15-libtiff-4.1.0-bin
      /nix/store/wb74cw6cz0bkf4q9jz4309pg3a8wlnm4-glibmm-2.64.2
      /nix/store/wdcv64vnzsygacwsh832cmkzrxr93437-at-spi2-core-2.36.1
      /nix/store/wj403fa87rhb443zzg71n4kj18jjmfxw-xkeyboard-config-2.27
      /nix/store/wsh174xyzi8vp20sii1w30pqslhpxrhg-python2.7-six-1.15.0
      /nix/store/wx6b5bzxaj2590mzg8c0amimyajgsarx-libXcomposite-0.4.5
      /nix/store/wzgqf12klflkwfn214dwy921n9kzyxvr-glib-2.64.5
      /nix/store/x4j34ihsc2pnwhdxmr1nhq48zjddvh8p-libXi-1.7.10
      /nix/store/x8jrrgzdmfkxw27v1k2gpvcg05bpyhiq-libjpeg-turbo-2.0.5
      /nix/store/xfsqg2zrh44m41i44g619snd2n7n66rm-sudo-1.9.3p1
      /nix/store/xlbd0pd961hz0pvajlirfvhpp1gd6187-zlib-1.2.11-dev
      /nix/store/xqkrvn9hxyh42si90vb8gm4m8p2i7xsf-libnftnl-1.1.7
      /nix/store/xrz4fd3a6gh43ilh018rm58g9bbgjbmi-libX11-1.6.12
      /nix/store/xvmcyr2rg2x8j18hqcihq80ggd358y0n-lz4-1.9.2-dev
      /nix/store/xvml5rwggm8im3qb5wl11sqjm2b6d7f0-libnfnetlink-1.0.1
      /nix/store/xxgzl9pjzj66j2wjnbxrz3z2sg2njvjf-postgresql-11.9-lib
      /nix/store/y27nxzzz8rmbni3gdn4dprbsvzbrxllk-libassuan-2.5.3
      /nix/store/y2yj882ygd8x059z5k6ybvdaxhgp0a3s-libgcrypt-1.8.6
      /nix/store/y6fpk57f7rsrkqbn5x2fli7lli2di530-gdal-3.1.2.post2020-08-26
      /nix/store/y7rwjnnzlxbijc7jpsyr4k7adnqwrpl7-lz4-1.9.2-bin
      /nix/store/ypih4394q488ljr421x8jak55vmr0ckn-glibc-2.32-dev
      /nix/store/yq97zmf6pxzl1dghf7p1nss34rbj8fxk-dconf-0.36.0-lib
      /nix/store/yqvyrz88vdmi7gizj4116jfxc4d6pjp1-proj-6.3.1
      /nix/store/zahjq1x7xjw26j7lv6xfnjc8d061y6lk-expand-response-params
      /nix/store/zh95n4gkak8jr3bwipkrg7mbx9qpqih9-audit-2.8.5
      /nix/store/znb3ffjhmpm25xxn0kkv4d5lkpq26a35-python2.7-pycparser-2.20
      /nix/store/zpsfaagvpz30j7rx1vw6plzjgv07ysyz-libevent-2.1.12-dev
      /nix/store/zqf19zrgpb4818j0h2z2i3gckcyxf152-pkg-config-wrapper-0.29.2
      /nix/store/zrzyhci4155qm17b4ijvmrxzhy1hssa9-wayland-1.18.0
      /nix/store/zwijq28q9l8yl0jy7qk3kyz6xi87bdhy-python2.7-pyasn1-0.4.8
      copying path '/nix/store/8kmia55bxccdvhx79hg6n56nhlqpw8j7-gsettings-desktop-schemas-3.36.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/aipbaqh6svp2mssslwlmxjwrlqgyvxxy-dejavu-fonts-minimal-2.37' from 'https://cache.nixos.org'...
      copying path '/nix/store/n3v2sbh4pvx8pvfnb13wg07vq9x7w9i7-dns-root-data-2019-01-11' from 'https://cache.nixos.org'...
      copying path '/nix/store/i8jx31d2lqh9f55w8vwlgyc1az3jp2pv-fontconfig-2.13.92' from 'https://cache.nixos.org'...
      copying path '/nix/store/3wsi43smyzkk0q2fb299yrrgriwilams-iso-codes-4.5.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/hfpiccrc1wsqv9p09mb2ddkakpg09bh4-libunistring-0.9.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/blk092jlzlqs4wrasfaciggwbxpbn694-linux-headers-5.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/7bpq6jhxdans9csm7brrdj0qg8bk0m8v-libidn2-2.3.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/rgisiwcvbwq76r1p4k9r3ybnzck95rkn-ncurses-6.2-man' from 'https://cache.nixos.org'...
      copying path '/nix/store/kah5n342wz4i0s9lz9ka4bgz91xa2i94-glibc-2.32' from 'https://cache.nixos.org'...
      copying path '/nix/store/6yfafnp1ssjksj6bnks969h8zanm7q6m-poppler-data-0.4.9' from 'https://cache.nixos.org'...
      copying path '/nix/store/gyfqw8k2ibhn6mcka9mcd7wcmq14cnmm-attr-2.4.48' from 'https://cache.nixos.org'...
      copying path '/nix/store/qdp56fi357fgxxnkjrwx1g67hrk775im-bash-4.4-p23' from 'https://cache.nixos.org'...
      copying path '/nix/store/fg73gb66fnzlv9b9kc1bn1zvdq6w2dn4-acl-2.2.53' from 'https://cache.nixos.org'...
      copying path '/nix/store/zh95n4gkak8jr3bwipkrg7mbx9qpqih9-audit-2.8.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/gkz2jxfg0zi1xyra1b8xlyiqb2ngaskd-bzip2-1.0.6.0.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/2shqhfsyzz4rnfyysbzgyp5kbfk29750-coreutils-8.32' from 'https://cache.nixos.org'...
      copying path '/nix/store/bnc6mfjy52lsr81ikyw3kdf7qdqabgvx-bzip2-1.0.6.0.1-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/zahjq1x7xjw26j7lv6xfnjc8d061y6lk-expand-response-params' from 'https://cache.nixos.org'...
      copying path '/nix/store/if61207y3w841nq428vqqr7dfsjryvxq-expat-2.2.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/2x8cm493hnkh2zxcich3fpm82m5vrpq8-fribidi-1.0.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/vd8zcniaj90hb8n445fv3pbf9s9674p6-expat-2.2.10-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/lhbdlbqbvmnl9842ag62bynmkgbnp3dq-gcc-9.3.0-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/pdkllhgmkwbp8hdgi3wjdvy1z49l1n1f-gdbm-1.18.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/23gri5n5jxn96jjr5p0rcy2145d6s1bl-db-4.8.30' from 'https://cache.nixos.org'...
      copying path '/nix/store/lkl6hyqyw9gvb93mbfbylgdhkbazs3l2-db-5.3.28' from 'https://cache.nixos.org'...
      copying path '/nix/store/159apbdmiwk945209nbq7jb6rnmh363d-geos-3.8.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/djg5df35m2wnvr9d974iz19gylk07yb9-giflib-5.2.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/8l6c599l07zw3bbsn270sm54hz4lyais-glibc-2.32-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/m24r30pk12ckb1hsr9ylg6i7r64jbg38-gmp-6.2.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/ypih4394q488ljr421x8jak55vmr0ckn-glibc-2.32-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/ikifbdvhhbh1il37lxlr87yb28xqj677-gnutar-1.32' from 'https://cache.nixos.org'...
      copying path '/nix/store/lfz94vh4m9c2aygrc48cdsn9pyb4d2d0-graphite2-1.3.14' from 'https://cache.nixos.org'...
      copying path '/nix/store/5h5qnaypmrc1d706w66vwhnynwh20qjm-gzip-1.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/h2irg7w6qjmpg6x3dhxw33f3glw3ak5x-icu4c-67.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/8f13dxfh1rs0zxb13m39hnsysapqg9vc-json-c-0.14' from 'https://cache.nixos.org'...
      copying path '/nix/store/c7q9fig0zp7v12ys4x8w43bysi8h2jqs-icu4c-67.1-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/77k2a0jm8n55ympnxqpwmzv4s2hdq69i-keyutils-1.6.3-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/hn84phnkxjn22skjjbrb2jv17xdjprzb-lcms2-2.11' from 'https://cache.nixos.org'...
      copying path '/nix/store/nccvgkfqfdslcjkh448lpchl69sajpny-libICE-1.0.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/0764z6qz8s7gkwas1i88zwvvbzpmivry-libXau-1.0.9' from 'https://cache.nixos.org'...
      copying path '/nix/store/cwbdra0bd32091s1vfrm7m4aq9xrb56r-libXdmcp-1.1.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/m295m7xbigkh40k4a0cxk16pj7d6h8wb-libapparmor-2.13.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/1lql50lys0rwn2102a4krpgcwi0ys4kz-libcap-2.44-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/dakvjq52bjajv6vskawim9fs3amqgfi5-libdaemon-0.14' from 'https://cache.nixos.org'...
      copying path '/nix/store/p7hfgpmdzxfbsxg9nn0bcz7nhmj32yh1-libevent-2.1.12' from 'https://cache.nixos.org'...
      copying path '/nix/store/nvjd9mkfqdzbgbw4gsrj98kvxda7piri-libffi-3.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/dc09a64gfksp9wi4gx1kxzwwzzw4bvq9-libgpg-error-1.38' from 'https://cache.nixos.org'...
      copying path '/nix/store/b5cws72ynps2xyhy74fxdqmsf7a8f472-libffi-3.3-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/y27nxzzz8rmbni3gdn4dprbsvzbrxllk-libassuan-2.5.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/y2yj882ygd8x059z5k6ybvdaxhgp0a3s-libgcrypt-1.8.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/3y1l12ydwzsa594ylzij36v7zjl54h1c-libiodbc-3.52.12' from 'https://cache.nixos.org'...
      copying path '/nix/store/7r9v0hzwrrm9lh6c990fflrzwi36j7hf-gnupg-2.2.23' from 'https://cache.nixos.org'...
      copying path '/nix/store/x8jrrgzdmfkxw27v1k2gpvcg05bpyhiq-libjpeg-turbo-2.0.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/5f61vfhr8rzyjywmrdzbxh3ych62xcri-libkrb5-1.18' from 'https://cache.nixos.org'...
      copying path '/nix/store/8k0i6x3nlbqjj4p0sc2jadc7l7by75x8-libjpeg-turbo-2.0.5-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/9svfnzisqwsxzc0av6yksh7b1pcbb553-libmnl-1.0.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/6wzc17mfz9qn9gbbp2kzhcaf7c80hgdl-libjpeg-turbo-2.0.5-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/xvml5rwggm8im3qb5wl11sqjm2b6d7f0-libnfnetlink-1.0.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/xqkrvn9hxyh42si90vb8gm4m8p2i7xsf-libnftnl-1.1.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/1fmgf62158i2ys89m4m983z4d8nx1630-libnetfilter_conntrack-1.0.8' from 'https://cache.nixos.org'...
      copying path '/nix/store/2kbpfcpagl62m17bg3apa6pm24vydny1-libossp-uuid-1.6.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/971nym7avrn2f99ng904rffcpbxjplbr-libpcap-1.9.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/6rxn3knmprqf2sd1gmbqrmxi2s538vnl-libseccomp-2.5.0-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/19p49h93x1zv7zmrpc3myrxr9c95w788-iptables-1.8.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/hq2qa8qfqycbq4yxmpakdydy347axm85-libsigc++-2.10.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/hcsw29r90klliqjyfi0z03qdbvg4hf73-libsodium-1.0.18' from 'https://cache.nixos.org'...
      copying path '/nix/store/f9b4nrlv3an2mqq6772h134za8f3z4rg-libtasn1-4.16.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/av86g78lzflpxhkq4g9i3r6ab5p1ri2v-libtirpc-1.2.7-rc4' from 'https://cache.nixos.org'...
      copying path '/nix/store/ayx1hkfwar23xvlfn4l7f8444fhmnmk7-libxcb-1.14' from 'https://cache.nixos.org'...
      copying path '/nix/store/kp4asqh3waln1m8wka8xbjna1lr7nfap-lz4-1.9.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/xrz4fd3a6gh43ilh018rm58g9bbgjbmi-libX11-1.6.12' from 'https://cache.nixos.org'...
      copying path '/nix/store/y7rwjnnzlxbijc7jpsyr4k7adnqwrpl7-lz4-1.9.2-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/wx6b5bzxaj2590mzg8c0amimyajgsarx-libXcomposite-0.4.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/qsg1y8zjvzad9lfvrzvkf7j6jcz8mzqc-libXext-1.3.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/w4rfml3w6v1jvpvixih50s12hwcsrjky-libXfixes-5.0.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/x4j34ihsc2pnwhdxmr1nhq48zjddvh8p-libXi-1.7.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/qmi3aqa54q02wl7km7i4w1c2ad04f7k0-libXdamage-1.1.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/1k6wsg0a3wlyfyfqfawyz3ccdba84mms-libXinerama-1.1.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/cyaf9gyinfhv7xzpnxsvfm0mg0haq21x-libXrender-0.9.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/j7hl2d7bwy0ih32002nilzvyy0dx8xyy-libXtst-1.2.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/1xm6cjbyv6005rxiqkzbavr9swmiygdm-libXcursor-1.2.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/hq75v8gmnxw132mcg0gxhwflsb3s1p7m-libXrandr-1.5.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/jq7ikqkazzazydfgghia6n1zww1nnbiq-libglvnd-1.3.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/xvmcyr2rg2x8j18hqcihq80ggd358y0n-lz4-1.9.2-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/cwc3rnn0lhpq77cwan20cji0w7lhg33y-libGL-1.3.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/ilvkcyc9h6b5vg8yxi8gbkajc9044jms-ncurses-6.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/daj9qsd3ickv1ygn37zmri0ir6wpqv53-epoxy-1.5.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/18lvqs6xfmda6rspfyklf3978a1axwrr-libedit-20191231-3.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/478qa0dmvj9d2ra9gpda0ykdpgj78nhp-nettle-3.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/m8pgg5z35bs01hyiirwmsv7z8qc8hhcf-nghttp2-1.41.0-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/qx10kf2vcysr0wvz09g2yh7vwpw0vpn2-numactl-2.0.14' from 'https://cache.nixos.org'...
      copying path '/nix/store/6p9bqmsl15490izwpzvjqhbfa271ni9y-openssl-1.1.1h' from 'https://cache.nixos.org'...
      copying path '/nix/store/mbszh64fss16x16nj4ffv28qlpdqybr6-p11-kit-0.23.21' from 'https://cache.nixos.org'...
      copying path '/nix/store/gxj03v97cb81039accdxgmmj8srhfbp1-libevent-2.1.12-openssl' from 'https://cache.nixos.org'...
      copying path '/nix/store/dpy5i9qymncg7brd2xi23k56ax9jg2zm-openssl-1.1.1h-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/zpsfaagvpz30j7rx1vw6plzjgv07ysyz-libevent-2.1.12-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/jx0ibjlcgljnkwzfj6ij4f763fsns8h0-openssl-1.1.1h-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/gnb3ix8dx5lghj5ccjlfi2kg4l76f8w4-pcre-8.44' from 'https://cache.nixos.org'...
      copying path '/nix/store/ajafywz2virg6zf1yvjwyls69x3ic60j-pcre2-10.35' from 'https://cache.nixos.org'...
      copying path '/nix/store/8kv1647yhqd13z571h56rgm2ldm567dm-gnugrep-3.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/9qh6ck8d9ill2zan91rsnf4ba30hpf95-libselinux-2.9' from 'https://cache.nixos.org'...
      copying path '/nix/store/d3vh8xya1pq91lmlh01j74wgb57g7qvv-pcre-cpp-8.44' from 'https://cache.nixos.org'...
      copying path '/nix/store/74sd6nrnxiafn2l4mdwz4h7wz2wnx90a-pixman-0.38.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/qh55gxy4a3msz4kf4iiq0d6zcpq01b54-pkg-config-0.29.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/fn7m5cg0r2806hl6rvm8088d8yzffrr5-popt-1.16' from 'https://cache.nixos.org'...
      copying path '/nix/store/zqf19zrgpb4818j0h2z2i3gckcyxf152-pkg-config-wrapper-0.29.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/165sgncsp2fmmjcibjihvfyvbdd5rsv4-qhull-2016.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/iq0m232p954skqpgjmwzxx88x9i956zw-re2-20201001' from 'https://cache.nixos.org'...
      copying path '/nix/store/p5iv8pdxi5r4xr65dm5wgr43pkxkjx16-readline-6.3p08' from 'https://cache.nixos.org'...
      copying path '/nix/store/w4fqg4x5dzblnib6sr1i75wq2w64hcl7-readline-7.0p5' from 'https://cache.nixos.org'...
      copying path '/nix/store/0f3ai525f7cmr65k7ni89crskjjj60cf-unbound-1.12.0-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/qghvmavv2qk81hbg06ghp7qpazvaibdh-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
      copying path '/nix/store/p71girl88aldyvn2g0h7pn4cjawdrgga-gnutls-3.6.15' from 'https://cache.nixos.org'...
      copying path '/nix/store/vwmjh73qqcn9djixalzpr0c02lqyhsix-unixODBC-2.3.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/vgss4yh5r7fq9pip7mk56dlksrw36h8m-util-linux-2.36' from 'https://cache.nixos.org'...
      copying path '/nix/store/wj403fa87rhb443zzg71n4kj18jjmfxw-xkeyboard-config-2.27' from 'https://cache.nixos.org'...
      copying path '/nix/store/m4wghpmj1vbmn2rqk3v19c5m9br03250-antlr-runtime-cpp-4.8' from 'https://cache.nixos.org'...
      copying path '/nix/store/ndfylywxzsc6dkp73cn1k7wdjmifjhbv-libSM-1.2.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/aa8wbrx8b9pjwa3wwdwhf51zmdli26hx-libxkbcommon-0.10.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/bxh0rnxyjqbbw2zvj9ajra169bcqwsr9-xz-5.2.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/8fcxqg8dmwlkjw2vgkgz607kr5jy552w-zlib-1.2.11' from 'https://cache.nixos.org'...
      copying path '/nix/store/91m1bh46fj3ykm45lb6kvh89il792pj9-kmod-27' from 'https://cache.nixos.org'...
      copying path '/nix/store/bnjps68g8ax6abzvys2xpx12imrx8949-binutils-2.31.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/mz45csnlzibkkrkdvkfm9cwq0j1lv5z7-boost-1.59.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/k3scwx9w0988csgnfy67cxlaj605g87i-binutils-wrapper-2.31.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/6cn64xk3n5723afx62f22ld77dil7cbc-boost-1.59.0-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/s3jhwif715gkhbrjhhb5pdv8lq3z2266-boost-1.69.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/r898vrribzgp9s502vhm0036nppyarpl-cracklib-2.9.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/g4gg2yqpv2lsj4vhrza1nijnzl07gg1c-boost-1.69.0-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/j2pvv7vdqkzhasxk5v3kix3xl68nhjgn-gcc-9.3.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/wzgqf12klflkwfn214dwy921n9kzyxvr-glib-2.64.5' from 'https://cache.nixos.org'...
      copying path '/nix/store/ppfvi0cfcpdr83klw5kx6si2l260n1gh-gcc-wrapper-9.3.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/qdxniv416wbcizfnqbajgq99q8sc1qrp-atk-2.36.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/yq97zmf6pxzl1dghf7p1nss34rbj8fxk-dconf-0.36.0-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/wb74cw6cz0bkf4q9jz4309pg3a8wlnm4-glibmm-2.64.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/4zxwvbg07ypnlh6r78kp3swcy93919a3-hdf-4.2.15' from 'https://cache.nixos.org'...
      copying path '/nix/store/03xvf19yd2d4j6f4ppanyxzhfv2b1h0z-atkmm-2.28.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/hgc32jc9wzg1l7xq69an3v6w9m0xj8f1-hdf-4.2.15-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/57yia67ixw99ahy6s5cal6y22kk1mcr5-hdf5-1.10.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/23r068n28wqhp619v4jw4cvlvs67xp6d-hdf-4.2.15-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/djkgh2mz72lgf849mpcpl2yzn84ibizs-kexec-tools-2.0.20' from 'https://cache.nixos.org'...
      copying path '/nix/store/bfr66vwyasj7km8zbxv41qiihlss9165-libpng-apng-1.6.37' from 'https://cache.nixos.org'...
      copying path '/nix/store/89xa9b33wlxhmkxhflp8gfdb8n2nn5y4-libsecret-0.20.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/06ymz7xipyybjn1pmxcpn3zzbm1bxk50-freetype-2.10.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/k4sdsvdnxpqckdjxjv0gr5x4jsv0ng4v-libssh-0.8.9' from 'https://cache.nixos.org'...
      copying path '/nix/store/3g1lrr95qmyc80gfn1n1mddx66d3p98r-fontconfig-2.13.92-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/78d1i8bhnd1flnxk1srpjm2fbdli6fls-harfbuzz-2.7.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/4rm9zps0vcz8f65jb8y41djdpllixbqx-cairo-1.16.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/q2k599dnhcs9p2j3wfiayan73q44w6y5-libXft-2.3.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/vjf88s0z78mhnyaggq2jw2a02zvgq1yj-cairomm-1.12.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/6lc0s5wnppzb1526vnlxiq34h1l01460-libssh2-1.9.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/fir9pdbqlvhr05hp9qvyd2nblac3lp60-libtiff-4.1.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/gqni3z3v5v824hq8f9j42s0l3j6318mz-curl-7.73.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/bbyw2n7f771z85nk647znlri22izwm2y-gdk-pixbuf-2.40.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/w6ly66j38ri54rc712vsl0zf46wz8q15-libtiff-4.1.0-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/i5iikq61lvkxvhbh5hpk4c1m6zw370pg-libxml2-2.9.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/027haj2r42a8997xy0gxszazdn5dpx9m-libzip-1.6.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/1nqmm3yj772g38vlrk2y80xy59vq0442-linux-pam-1.3.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/9xnc99n9lvv59nwad16zi73bi3z83z8v-ncurses-6.2-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/622p9d64jgzdka252fzd17ljxs3m3ar2-kbd-2.0.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/sha4zfj4awli9mrmyzsyaph2pamlck0j-libedit-20191231-3.1-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/jjh1gjjzg4hl10mhy3lblcjinywcn5hl-netcdf-4.7.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/mk5fx9wbsqrbknp6mazgab9vmg336609-openjpeg-2.3.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/42n8wzfsd98xh9i02sm9ikzsxi2921ja-pango-1.45.3' from 'https://cache.nixos.org'...
      copying path '/nix/store/2l0kc0lx8122pbzysm2ss5xscirq0j33-poppler-glib-20.08.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/5pq125diq416cz6fvam7mf7c65c09imw-librsvg-2.48.8' from 'https://cache.nixos.org'...
      copying path '/nix/store/09v32i77zl9dpy0wyfvh5w60mjcn5qnc-pangomm-2.42.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/xxgzl9pjzj66j2wjnbxrz3z2sg2njvjf-postgresql-11.9-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/q06qb43z9inljcl8yjp8ll7ihhjkavs0-protobuf-3.7.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/dahgbm8aivbr50w80mjrwzs8nsh9a253-shadow-4.8.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/dzj9gs5iir5j8nn2wshsh6i9l6v4zqli-mysql-5.7.27' from 'https://cache.nixos.org'...
      copying path '/nix/store/hr43hbclvklvs08qg9y24pg77nrsmbgl-mysql-8.0.17' from 'https://cache.nixos.org'...
      copying path '/nix/store/9myly8vmha57m1jwrlxzhsvkiamvl97x-sqlite-3.33.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/kd8i2i3pldbzihcdpv6qgskgxc59374f-libmysqlconnectorcpp-8.0.21' from 'https://cache.nixos.org'...
      copying path '/nix/store/yqvyrz88vdmi7gizj4116jfxc4d6pjp1-proj-6.3.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/vhcx1a5m9xscxrmmz7s4nllhcfg5axnn-python-2.7.18' from 'https://cache.nixos.org'...
      copying path '/nix/store/2fz4hd2gw73y7di274bdpq0bw2hxnfqa-libgeotiff-1.5.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/w59b1g3hd5gvwrj21qh38glpywia8lvk-libspatialite-4.3.0a' from 'https://cache.nixos.org'...
      copying path '/nix/store/a832yyp1xziag0h0kvy8zrcqwzkzy7hg-proj-6.3.1-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/aj29saxhbnw9ng35ix46rnzfyvpnaxsm-python2.7-cffi-1.14.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/f9jcpi36wgwvf1lh7c68mx7k87xihgqz-python2.7-cryptography-2.9.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/m67p7i8a45hpd51jjjq39j19vis3wpzs-python2.7-enum34-1.1.10' from 'https://cache.nixos.org'...
      copying path '/nix/store/k9v26smi1999sc167xy7v3bab9sybzk2-python2.7-ipaddress-1.0.23' from 'https://cache.nixos.org'...
      copying path '/nix/store/zwijq28q9l8yl0jy7qk3kyz6xi87bdhy-python2.7-pyasn1-0.4.8' from 'https://cache.nixos.org'...
      copying path '/nix/store/h7x67w9f6fqyyyf31lc0df8xngchck7f-python2.7-pycairo-1.18.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/znb3ffjhmpm25xxn0kkv4d5lkpq26a35-python2.7-pycparser-2.20' from 'https://cache.nixos.org'...
      copying path '/nix/store/qp3pb6bqr5mixb0mmyhrkiq887iy21ms-python2.7-pyodbc-4.0.30' from 'https://cache.nixos.org'...
      copying path '/nix/store/42dx4mzml1jq6p9mjrlm1zimywq1n0r8-python2.7-cffi-1.14.2-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/va2f97v8n2rwnzc7qqy6x6c8rd21nkm9-python2.7-pyparsing-2.4.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/wsh174xyzi8vp20sii1w30pqslhpxrhg-python2.7-six-1.15.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/gvkhgh813chlsvdsnxgwhv72xns08xcp-python3-3.8.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/pk1hwhw97bsm325gy15v6340m2zh2va7-python2.7-bcrypt-3.1.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/g6z1kb94ff1x959jbj2mnx8rbmapb4ij-python2.7-packaging-20.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/5mzp7cdjlwmj29cvyba2ag3s1p96lfpc-python2.7-pynacl-1.4.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/k8w6yphs1c5a4d5x0ask5k8ycxpp8q7b-python2.7-cryptography-2.9.2-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/apni99c9rdaii9xvsmf1x65dvwgsaxj0-sqlite-3.33.0-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/10k4rvwvsvb65jywky7sd5626jaby4s6-python2.7-paramiko-2.7.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/fq884ddqqa9pg5gxngi1534g81ns2bf3-sqlite-3.33.0-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/xfsqg2zrh44m41i44g619snd2n7n66rm-sudo-1.9.3p1' from 'https://cache.nixos.org'...
      copying path '/nix/store/r9h30mp69zcrj8ia0bs98qi1cvkw0ira-util-linux-2.36-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/rrl72irws5nay6bkylj6swh8j6k1lnll-vsqlite-0.3.13' from 'https://cache.nixos.org'...
      copying path '/nix/store/vwlk07g63fdlmdbvikka1wgb0k9nsg0c-systemd-minimal-246.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/zrzyhci4155qm17b4ijvmrxzhy1hssa9-wayland-1.18.0' from 'https://cache.nixos.org'...
      copying path '/nix/store/3725gkhcvwdknqp0b51mx7wpva56faxr-lvm2-2.03.10-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/nichvfjqdfimxmvlhg5q1gs3agiyw9nc-xz-5.2.5-bin' from 'https://cache.nixos.org'...
      copying path '/nix/store/vy72w62ndpnhwb3wkdq89bbxvg2vqndh-cryptsetup-2.3.4' from 'https://cache.nixos.org'...
      copying path '/nix/store/f2ix29b5yp5zjl4sxsy6xj4n775qa43d-xz-5.2.5-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/kvsxb0p4qg5s639ngnix9vphcpcr2q2y-systemd-246.6' from 'https://cache.nixos.org'...
      copying path '/nix/store/xlbd0pd961hz0pvajlirfvhpp1gd6187-zlib-1.2.11-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/clnhaz7q45hna5xj0x7lmayc0hr3mzd3-dbus-1.12.20-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/12smikrbb26awn8kb93jzgjibda9i9j9-libpng-apng-1.6.37-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/wdcv64vnzsygacwsh832cmkzrxr93437-at-spi2-core-2.36.1' from 'https://cache.nixos.org'...
      copying path '/nix/store/b6h8w51kl4cpv3r2h6xrpr3injqh99yy-avahi-0.7' from 'https://cache.nixos.org'...
      copying path '/nix/store/4bz9ysliadpg73rm0h0gc87b0cpjg19m-at-spi2-atk-2.34.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/1qv0pm4j52lfagsw90ax8przd0cfg8cz-cups-2.3.3-lib' from 'https://cache.nixos.org'...
      copying path '/nix/store/s06hrsni6mxxf3lh61zbznhj0qxy37nr-libtiff-4.1.0-dev' from 'https://cache.nixos.org'...
      copying path '/nix/store/rhmffz05dz4zp9szpyrxazd4yz8im38p-gtk+3-3.24.21' from 'https://cache.nixos.org'...
      copying path '/nix/store/y6fpk57f7rsrkqbn5x2fli7lli2di530-gdal-3.1.2.post2020-08-26' from 'https://cache.nixos.org'...
      copying path '/nix/store/mmbd63kk9r0yi1mppxcwacw7pn9n4x5j-gtkmm-3.24.2' from 'https://cache.nixos.org'...
      copying path '/nix/store/cghlhk1j0s07mv08vg4wxsn514lzmyzi-mysql-workbench-8.0.21' from 'https://cache.nixos.org'...
      building '/nix/store/459mzml0n5dr7my0hnmnza89ygsr7x71-user-environment.drv'...
      created 566 symlinks in user environment

**** Run
     $ mysql-workbench
*** MySQL Version 8.0.22
    -> https://github.com/docker-library/mysql/blob/ee33a2144a0effe9459abf02f20a6202ae645e94/8.0/Dockerfile.debian

**** Run/stop/remove MySQL db container
     $ docker run --name manning-mysql -e MYSQL_ROOT_PASSWORD=secret -p 3306:3306 -d mysql:8.0.22
     $ docker stop manning-mysql
     $ docker rm manning-mysql
***** Log
      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ docker run --name manning-mysql -e MYSQL_ROOT_PASSWORD=secret -p 3306:3306 -d mysql:8.0.22
      Unable to find image 'mysql:8.0.22' locally
      8.0.22: Pulling from library/mysql
      852e50cd189d: Pull complete 
      29969ddb0ffb: Pull complete 
      a43f41a44c48: Pull complete 
      5cdd802543a3: Pull complete 
      b79b040de953: Pull complete 
      938c64119969: Pull complete 
      7689ec51a0d9: Pull complete 
      a880ba7c411f: Pull complete 
      984f656ec6ca: Pull complete 
      9f497bce458a: Pull complete 
      b9940f97694b: Pull complete 
      2f069358dc96: Pull complete 
      Digest: sha256:4bb2e81a40e9d0d59bd8e3dc2ba5e1f2197696f6de39a91e90798dd27299b093
      Status: Downloaded newer image for mysql:8.0.22
      a97b4bb397956ff8f30da99c4d5e87d70a07bc7a693aebc884dc719a6393d94a

      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ docker ps
      CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
      a97b4bb39795        mysql:8.0.22        "docker-entrypoint.s…"   35 seconds ago      Up 33 seconds       0.0.0.0:3306->3306/tcp, 33060/tcp   manning-mysql

      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ docker exec -it manning-mysql mysql -P 3306 -u root --password=secret
      mysql: [Warning] Using a password on the command line interface can be insecure.
      Welcome to the MySQL monitor.  Commands end with ; or \g.
      Your MySQL connection id is 8
      Server version: 8.0.22 MySQL Community Server - GPL

      Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

      Oracle is a registered trademark of Oracle Corporation and/or its
      affiliates. Other names may be trademarks of their respective
      owners.

      Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

      mysql> \h

      For information about MySQL products and services, visit:
      http://www.mysql.com/
      For developer information, including the MySQL Reference Manual, visit:
      http://dev.mysql.com/
      To buy MySQL Enterprise support, training, or other products, visit:
      https://shop.mysql.com/

      List of all MySQL commands:
      Note that all text commands must be first on line and end with ';'
      ?         (\?) Synonym for `help'.
      clear     (\c) Clear the current input statement.
      connect   (\r) Reconnect to the server. Optional arguments are db and host.
      delimiter (\d) Set statement delimiter.
      edit      (\e) Edit command with $EDITOR.
      ego       (\G) Send command to mysql server, display result vertically.
      exit      (\q) Exit mysql. Same as quit.
      go        (\g) Send command to mysql server.
      help      (\h) Display this help.
      nopager   (\n) Disable pager, print to stdout.
      notee     (\t) Don't write into outfile.
      pager     (\P) Set PAGER [to_pager]. Print the query results via PAGER.
      print     (\p) Print current command.
      prompt    (\R) Change your mysql prompt.
      quit      (\q) Quit mysql.
      rehash    (\#) Rebuild completion hash.
      source    (\.) Execute an SQL script file. Takes a file name as an argument.
      status    (\s) Get status information from the server.
      system    (\!) Execute a system shell command.
      tee       (\T) Set outfile [to_outfile]. Append everything into given outfile.
      use       (\u) Use another database. Takes database name as argument.
      charset   (\C) Switch to another charset. Might be needed for processing binlog with multi-byte charsets.
      warnings  (\W) Show warnings after every statement.
      nowarning (\w) Don't show warnings after every statement.
      resetconnection(\x) Clean session context.

      For server side help, type 'help contents'

      mysql> \q
      Bye
      bert@bert-K18Base:~/DistributedGridProject/manning-energy-resources/scaffold$ 

**** Connect to the db conatiner via CLI
     $ docker exec -it manning-mysql mysql -P 3306 -u root --password=secret
**** Enable the mysql dependency in the pom, adding the client libraries to the project , allowing you to actually connect to the database
**** Add to [[file:///home/bert/DistributedGridProject/manning-energy-resources/scaffold/ingestbattevents.yml][ingestbattevents.yml]]
     database:
       driverClass: com.mysql.cj.jdbc.Driver
       user: root
       password: secret
       url: "jdbc:mysql://0.0.0.0:3306/information_schema"
* Local variables
# Local Variables:
# org-confirm-babel-evaluate: nil
# eval: (progn (org-babel-goto-named-src-block "helper_functions ") (org-babel-execute-src-block) (outline-hide-sublevels 1))
# eval: (progn (org-babel-goto-named-src-block "pojo_functions ") (org-babel-execute-src-block) (outline-hide-sublevels 1))
# eval: (progn (org-babel-goto-named-src-block "avro_functions ") (org-babel-execute-src-block) (outline-hide-sublevels 1))
# eval: (progn (org-babel-goto-named-src-block "dbi_functions ") (org-babel-execute-src-block) (outline-hide-sublevels 1))
# End:
